name: Dans site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbe4f6'
    - '#24304a'
    - '#ffcc4d'
    - '#de2e45'
    - '#77b256'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
